//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitElementsElevation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitElementsElevation.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families are not found. Please check Settings..
        /// </summary>
        public static string ErrorFamiliesNotFound {
            get {
                return ResourceManager.GetString("ErrorFamiliesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the base level for the element.
        /// </summary>
        public static string ErrorNoLevel1 {
            get {
                return ResourceManager.GetString("ErrorNoLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on level .
        /// </summary>
        public static string ErrorNoLevel2 {
            get {
                return ResourceManager.GetString("ErrorNoLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process: .
        /// </summary>
        public static string MessageFamiliesNotProceed {
            get {
                return ResourceManager.GetString("MessageFamiliesNotProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families processed:.
        /// </summary>
        public static string MessageFamiliesProceed {
            get {
                return ResourceManager.GetString("MessageFamiliesProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openings are found: .
        /// </summary>
        public static string MessageOpeningsFound {
            get {
                return ResourceManager.GetString("MessageOpeningsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also walls and columns processed: .
        /// </summary>
        public static string MessageWallAndColumns {
            get {
                return ResourceManager.GetString("MessageWallAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.BaseLevelElevation.
        /// </summary>
        public static string ParameterBaseLevelElev {
            get {
                return ResourceManager.GetString("ParameterBaseLevelElev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.BottomElevation.
        /// </summary>
        public static string ParameterBottomElev {
            get {
                return ResourceManager.GetString("ParameterBottomElev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.OffsetFromLevel.
        /// </summary>
        public static string ParameterElevFromLevel {
            get {
                return ResourceManager.GetString("ParameterElevFromLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.TopElevation.
        /// </summary>
        public static string ParameterTopElev {
            get {
                return ResourceManager.GetString("ParameterTopElev", resourceCulture);
            }
        }
    }
}
